name: Build and Publish Python Plugin Package

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # See: https://docs.pypi.org/trusted-publishers/using-a-publisher/
    environment: pypi
    permissions:
      id-token: write

    defaults:
      run:
        working-directory: public/plugin/python

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Build the package with uv
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
        with:
          packages-dir: public/plugin/python/dist

