name: Test Plugin Uploader

on:
  push:
    branches:
      - main
    paths:
      - 'resources/plugin_uploader/**'
      - '.github/workflows/test_plugin_uploader.yml'
  pull_request:
    paths:
      - 'resources/plugin_uploader/**'
      - '.github/workflows/test_plugin_uploader.yml'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - working-directory: resources/plugin_uploader
        run: pip install -r requirements_test.txt

      - working-directory: resources/plugin_uploader
        run: pytest -vv .

  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - name: Lint with Ruff
        working-directory: resources/plugin_uploader
        run: |
          pip install ruff==0.4.10
          ruff check --output-format=github

  pyright-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - working-directory: resources/plugin_uploader
        run: pip install -r requirements_test.txt

      - run: pip install pyright==1.1.378

      - working-directory: resources/plugin_uploader
        run: pyright
